### ISSUE TITLE
links open blank page in IE

### ISSUE THREAD

**Issue by loganSims** [WSDOT/search-analytics-console#2]

**Comment by waynedyck** [comment]
You could likely fix this by adding the following after the opening `<head>` tag
```
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
```
Otherwise, our IE browsers are set to default to something like IE 7 compatibility mode.

**Comment by waynedyck** [comment]
IE just shouldn't be used any more. Use either Chrome or Edge.
